version: "3.8"

services:
  client:
    build: ./client
    image: client:latest
  server:
    build: ./server
    image: server:latest
    ports:
      - 8080:8080
  redis:
    image: bitnami/redis:6.2
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes