POST http://localhost:8080/signup

{"name": "Carlo", "credentials": {"username": "carlomendoza", "password": "123"}}

POST http://localhost:8080/signin

{"username": "carlomendoza", "password": "123"}