POST http://localhost:8080/signup

{"username": "cmendoza", "password": "123"}

###

POST http://localhost:8080/signin

{"username": "cmendoza", "password": "123"}

###

GET http://localhost:8080/transactions

###

POST http://localhost:8080/transactions

{"amount": 100, "date":"02-04-2022", "category_id": 1}

###

PUT http://localhost:8080/transactions

###

DELETE http://localhost:8080/transactions

###

GET http://localhost:8080/transactions/1

###

POST http://localhost:8080/transactions/1

###

PUT http://localhost:8080/transactions/1

{"amount": 200, "date":"02-04-2022", "notes": "Lunch out", "category_id": 2}

###

DELETE http://localhost:8080/transactions/1

###

GET http://localhost:8080/categories